version: '3.4'

# general python base for future services like celery
x-base-python: &x-base-python
  build:
    context: .
    dockerfile: ./Dockerfile
  image: app_template
  environment:
    - PYTHONUNBUFFERED=1
  restart: always



services:
  app:
    <<: *x-base-python
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    #uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000 #poetry run python3 -m app
    container_name: app_template
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    hostname: app
    volumes:
      - .:/srv/

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PYTHONPATH=.
#    env_file:
#      - dev.env
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
#    tmpfs: /var/lib/pgsql/

